language: python

branches:
  only:
    - /.*/

python:
  - "2.7_with_system_site_packages"
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - libwww-perl
      - libcss-dom-perl
      - python-lxml
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - nvm install 8
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
  - sh -e /etc/init.d/xvfb start
install:
 - make travissetup
script:
 - make check

env:
  global:
    - URL="https://w3c.github.io/mediacapture-screen-share/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0031.html"
    - secure: "JATWG7VDH4Z9YpGWfkSgBc/p4gRZDdBcPCcS8qRPJp9APrdLaycyhvJisa2tWxt8mzKVC9FUA8pcY0uy8g4AL/fxLDdOzfdgP11Fti7m1OU7BsGxJ3duh/t3cgqy2zN8XpzZE3cTqQdVObzNdvKsjGB1sCUSIx5HE6FxF7KtgVA="

after_success:
  - test $TRAVIS_BRANCH = "gh-pages" -a $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
